[package]
name = "melody-matcher"
version = "1.0.0"
edition = "2021"

[dependencies]
eframe = "0.27"
egui = "0.27"
rfd = "0.14"
symphonia = { version = "0.5", features = ["all"] }
pitch-detection = "0.5"
midly = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "z"      # 最小体积
lto = true
strip = true
panic = "abort"
