#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""生成「公开开放曲库」索引（music21 内置公共领域曲库 -> 音程索引）。

产出两个文件（均在仓库根目录，已被 .gitignore 忽略，不入库）：
  1. public_corpus_index.json   —— 明文索引（约 15000+ 首，约 3.5MB）
  2. public_corpus_data.py      —— 内嵌索引模块（供打包进 EXE 时内存加载，
                                    避免部分系统上临时目录被杀毒软件锁文件）

用法：
  pip install music21          # 仅构建期需要
  python tools/build_public.py

原理：music21 仅用于"定位其内置 ABC 曲库目录"，曲库解析完全用本项目的
melody_engine.abc_to_pcs（纯 Python，不调用 music21 解析器），速度快、无重依赖。
索引内容为每首曲子的「有符号音程序列」（移调/变速不变），不存储任何音频。
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

import melody_engine as me  # noqa: E402


import base64 as _b64
import json as _json
import zlib as _zlib


def _wrap_b85(data, width=200):
    """把 bytes 编成 base85，并按行切成可读的 Python 字节字面量片段。"""
    s = _b64.b85encode(data).decode('ascii')
    lines = [s[i:i + width] for i in range(0, len(s), width)]
    return '\n'.join("    b'%s'" % ln for ln in lines)


def main():
    out_json = os.path.join(ROOT, me.PUBLIC_INDEX_NAME)
    n = me.build_public_index(out_json)
    print(f"[1/3] 索引：{n} 首 -> {out_json}")

    with open(out_json, 'r', encoding='utf-8') as f:
        idx = json.load(f)

    out_titles = os.path.join(ROOT, me.PUBLIC_TITLES_NAME)
    with open(out_titles, 'r', encoding='utf-8') as f:
        titles = json.load(f)
    named = sum(1 for v in titles.values() if v)
    print(f"[2/3] 曲名表：{named}/{len(titles)} 首有可读曲名 -> {out_titles}")

    # 内嵌模块：数据以 zlib 压缩 + base85 编码，导入时解压。
    # 直接写成超大 Python 字面量会让 .pyc 严重膨胀（本数据 3.9MB 源码 -> 5.4MB pyc），
    # 压缩后仅约 1.3MB，单文件 EXE 因此少约 2.5MB。
    payload = json.dumps({'i': idx, 't': titles}, ensure_ascii=False,
                         separators=(',', ':')).encode('utf-8')
    blob = _zlib.compress(payload, 9)
    mod = os.path.join(ROOT, 'public_corpus_data.py')
    with open(mod, 'w', encoding='utf-8') as f:
        f.write('# -*- coding: utf-8 -*-\n')
        f.write('# AUTO-GENERATED by tools/build_public.py. Do not edit by hand.\n')
        f.write('# 来源：music21 内置公共领域 ABC 曲库（传统/民间曲调为主）。\n')
        f.write('# 数据以 zlib 压缩 + base85 内嵌，导入时解压，避免大 Python 字面量的体积膨胀。\n')
        f.write('import base64 as _b64\n')
        f.write('import json as _json\n')
        f.write('import zlib as _zlib\n\n')
        f.write('# zlib-compressed (JSON: {i: index, t: titles}), base85-encoded\n')
        f.write('_BLOB = (\n')
        f.write(_wrap_b85(blob))
        f.write('\n)\n\n\n')
        f.write('def _load():\n')
        f.write('    try:\n')
        f.write('        raw = _zlib.decompress(_b64.b85decode(_BLOB))\n')
        f.write("        d = _json.loads(raw.decode('utf-8'))\n")
        f.write("        return d.get('i', {}), d.get('t', {})\n")
        f.write('    except Exception:\n')
        f.write('        return {}, {}\n\n\n')
        f.write('PUBLIC_INDEX, PUBLIC_TITLES = _load()\n')
    print(f"[3/3] 内嵌模块：{mod}  ({os.path.getsize(mod) // 1024} KB, "
          f"压缩前 {len(payload) // 1024} KB)")
    print("完成。现在可运行 `pyinstaller build_exe.spec` 打包单文件 EXE。")


if __name__ == '__main__':
    main()
